name: next-app-boilerplate

services:
    webserver:
        image: cyrus01337/next-app-boilerplate:production
        restart: always
        ports:
            - "3000:3000"

    reverse-proxy:
        depends_on:
            - webserver
        image: caddy:2.7.6-alpine
        restart: always
        cap_add:
            - NET_ADMIN
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - reverse-proxy-configuration:/config
            - reverse-proxy-data:/data

volumes:
    reverse-proxy-configuration:
    reverse-proxy-data:
