import Head from "next/head";

export default function Layout({ className, children }) {
    return (
        <>
            <Head>
                <title>Next App Boilerplate</title>
                <meta
                    content="Generated by create next app"
                    name="description"
                />
                <link href="/favicon.png" rel="icon" />
            </Head>

            <main className={className}>{children}</main>
        </>
    );
}
